export class Satellite {
  constructor (
    public Name: string,
    public CountryOrgUnRegistry: string,
    public CountryOperatorOwner: string,
    public OperatorOwner: string,
    public Users: string,
    public Purpose: string,
    public DetailedPurpose: string,
    public ClassofOrbit: string,
    public TypeOfOrbit: string,
    public LongitudeOfGEODegrees: number,
    public PerigeeKM: number,
    public ApogeeKM: number,
    public Eccentricity: number,
    public InclinationDegrees: number,
    public PeriodMinutes: number,
    public LaunchMassKG: number,
    public DryMassKG: string,
    public PowerWatts: string,
    public DateOfLaunch: string,
    public ExpectedLifetime: string,
    public Contractor: string,
    public CountryOfContractor: string,
    public LaunchSite: string,
    public LaunchVehicle: string,
    public COSPARNumber: string,
    public NORADNumber: number,
    public Comments: string,
    public SourceUsedForOrbitalData: string,
    public Source1: string,
    public Source2: string,
    public Source3: string,
    public Source4: string,
    public Source5: string
  ) { }
}


// export class Satellite {
//   constructor (
//     public Name: string,
//     public CountryOrgUnRegistry: string,
//     public CountryOperatorOwner: string,
//     public OperatorOwner: string,
//     public Users: string,
//     public Purpose: string,
//     public DetailedPurpose: string,
//     public ClassofOrbit: string,
//     public TypeOfOrbit: string,
//     public LongitudeOfGEODegrees: number,
//     public PerigeeKM: number,
//     public ApogeeKM: number,
//     public Eccentricity: number,
//     public InclinationDegrees: number,
//     public PeriodMinutes: number,
//     public LaunchMassKG: number,
//     public DryMassKG: string,
//     public PowerWatts: string,
//     public DateOfLaunch: string,
//     public ExpectedLifetime: string,
//     public Contractor: string,
//     public CountryOfContractor: string,
//     public LaunchSite: string,
//     public LaunchVehicle: string,
//     public COSPARNumber: string,
//     public NORADNumber: number,
//     public Comments: string,
//     public SourceUsedForOrbitalData: string,
//     public Source1: string,
//     public Source2: string,
//     public Source3: string,
//     public Source4: string,
//     public Source5: string
//   ) { }
// }
